//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace World_of_books.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int ID { get; set; }
        public int IdOrder { get; set; }
        public int IdBook { get; set; }
        public int IdTypeBook { get; set; }
        public int Count { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
        public virtual TypeBook TypeBook { get; set; }
    }
}
